apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-external-secrets
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    app.kubernetes.io/instance: kubernetes-external-secrets
