apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-external-secrets
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    app.kubernetes.io/instance: kubernetes-external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-external-secrets
subjects:
  - name: kubernetes-external-secrets
    namespace: kubernetes-external-secrets
    kind: ServiceAccount
