apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-external-secrets
  labels:
    app.kubernetes.io/instance: kubernetes-external-secrets
    app.kubernetes.io/name: kubernetes-external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-external-secrets
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubernetes-external-secrets
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      serviceAccountName: RELEASE-NAME-kubernetes-external-secrets
      containers:
        - name: kubernetes-external-secrets
          image: ghcr.io/external-secrets/kubernetes-external-secrets
          imagePullPolicy: IfNotPresent
          ports:
          - name: prometheus
            containerPort: 3001
